#!/usr/bin/env node
const pptxgen = require("pptxgenjs");
const fs = require("fs");

const args = process.argv.slice(2);
let title = "Document Title";
let output = "output.pptx";
let accentColor = "22223b";

for (let i = 0; i < args.length; i++) {
  if (args[i] === "--title" && args[i + 1]) title = args[++i];
  if (args[i] === "--output" && args[i + 1]) output = args[++i];
  if (args[i] === "--accent" && args[i + 1]) accentColor = args[++i];
}

const pres = new pptxgen();
pres.layout = 'LAYOUT_16x9';
pres.title = title;
pres.author = 'Generated by doc-to-ppt-pdf';

const theme = {
  primary: accentColor,
  secondary: "4a4e69",
  accent: "9a8c98",
  light: "c9ada7",
  bg: "f2e9e4",
  white: "FFFFFF"
};

function addCover() {
  const slide = pres.addSlide();
  slide.background = { color: theme.primary };

  slide.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.08, h: 5.625,
    fill: { color: theme.accent }
  });

  slide.addShape(pres.shapes.RECTANGLE, {
    x: 7.5, y: 4.2, w: 2.5, h: 1.425,
    fill: { color: theme.secondary, transparency: 60 }
  });

  slide.addText(title, {
    x: 0.6, y: 2.0, w: 8.5, h: 1.2,
    fontSize: 48, fontFace: "Microsoft YaHei",
    color: theme.white, bold: true, align: "left"
  });

  slide.addText("Generated Presentation", {
    x: 0.6, y: 3.4, w: 8, h: 0.5,
    fontSize: 20, fontFace: "Microsoft YaHei",
    color: theme.accent, align: "left"
  });
}

function addToc(sections) {
  const slide = pres.addSlide();
  slide.background = { color: theme.bg };

  slide.addText("目录", {
    x: 0.5, y: 0.4, w: 3, h: 0.7,
    fontSize: 32, fontFace: "Microsoft YaHei",
    color: theme.primary, bold: true
  });

  slide.addShape(pres.shapes.RECTANGLE, {
    x: 0.5, y: 1.0, w: 1.5, h: 0.06,
    fill: { color: theme.accent }
  });

  const startY = 1.4;
  const colWidth = 4.2;

  sections.forEach((sec, i) => {
    const col = i < 4 ? 0 : 1;
    const row = i % 4;
    const x = 0.5 + col * colWidth;
    const y = startY + row * 0.95;

    slide.addShape(pres.shapes.OVAL, {
      x: x, y: y + 0.1, w: 0.5, h: 0.5,
      fill: { color: theme.primary }
    });

    slide.addText(String(i + 1).padStart(2, '0'), {
      x: x, y: y + 0.1, w: 0.5, h: 0.5,
      fontSize: 14, fontFace: "Arial",
      color: theme.white, bold: true,
      align: "center", valign: "middle"
    });

    slide.addText(sec, {
      x: x + 0.65, y: y + 0.12, w: 3.2, h: 0.5,
      fontSize: 16, fontFace: "Microsoft YaHei",
      color: theme.secondary
    });
  });

  addPageNumber(slide, 2);
}

function addSectionSlide(sectionNum, sectionTitle, content) {
  const slide = pres.addSlide();
  slide.background = { color: theme.primary };

  slide.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.08, h: 5.625,
    fill: { color: theme.accent }
  });

  slide.addText(sectionNum, {
    x: 0.5, y: 0.5, w: 0.6, h: 0.6,
    fontSize: 28, fontFace: "Arial",
    color: theme.accent, bold: true
  });

  slide.addText(sectionTitle, {
    x: 1.2, y: 0.55, w: 6, h: 0.5,
    fontSize: 24, fontFace: "Microsoft YaHei",
    color: theme.white, bold: true
  });

  if (typeof content === 'string') {
    slide.addText(content, {
      x: 0.5, y: 1.5, w: 9, h: 3.5,
      fontSize: 16, fontFace: "Microsoft YaHei",
      color: theme.light
    });
  } else if (Array.isArray(content)) {
    let y = 1.5;
    content.forEach(item => {
      if (item.type === 'bullet') {
        slide.addText("•  " + item.text, {
          x: 0.7, y: y, w: 8.5, h: 0.4,
          fontSize: 14, fontFace: "Microsoft YaHei",
          color: theme.light
        });
        y += 0.45;
      } else if (item.type === 'callout') {
        slide.addShape(pres.shapes.RECTANGLE, {
          x: 0.5, y: y, w: 9, h: 0.8,
          fill: { color: theme.secondary, transparency: 70 }
        });
        slide.addText(item.text, {
          x: 0.7, y: y + 0.15, w: 8.6, h: 0.5,
          fontSize: 13, fontFace: "Microsoft YaHei",
          color: theme.white, italic: true
        });
        y += 0.95;
      }
    });
  }

  addPageNumber(slide, sectionNum);
}

function addTableSlide(title, headers, rows) {
  const slide = pres.addSlide();
  slide.background = { color: theme.bg };

  slide.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 10, h: 1.0,
    fill: { color: theme.primary }
  });

  slide.addText(title, {
    x: 0.5, y: 0.25, w: 9, h: 0.5,
    fontSize: 20, fontFace: "Microsoft YaHei",
    color: theme.white, bold: true
  });

  const tableData = [headers, ...rows];
  slide.addTable(tableData, {
    x: 0.5, y: 1.3, w: 9, h: 3.5,
    colW: [3, 3, 3],
    fontSize: 11,
    fontFace: "Microsoft YaHei",
    color: theme.secondary,
    border: { pt: 0.5, color: theme.accent },
    fill: { color: theme.white },
    rowH: 0.45,
    valign: "middle",
    align: "center"
  });

  addPageNumber(slide);
}

function addThankYou(whyContent) {
  const slide = pres.addSlide();
  slide.background = { color: theme.primary };

  slide.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.08, h: 5.625,
    fill: { color: theme.accent }
  });

  slide.addText("THANK YOU", {
    x: 0.6, y: 2.0, w: 9, h: 1,
    fontSize: 48, fontFace: "Arial",
    color: theme.white, bold: true, align: "center"
  });

  if (whyContent) {
    slide.addText(whyContent, {
      x: 0.6, y: 3.2, w: 8.8, h: 1.5,
      fontSize: 14, fontFace: "Microsoft YaHei",
      color: theme.light, align: "center"
    });
  }

  addPageNumber(slide);
}

function addPageNumber(slide, num) {
  const pageNum = num || "X";
  slide.addShape(pres.shapes.OVAL, {
    x: 9.3, y: 5.1, w: 0.4, h: 0.4,
    fill: { color: theme.accent }
  });
  slide.addText(String(pageNum), {
    x: 9.3, y: 5.1, w: 0.4, h: 0.4,
    fontSize: 10, fontFace: "Arial",
    color: theme.white, bold: true,
    align: "center", valign: "middle"
  });
}

function generateDefaultPresentation() {
  addCover();

  addToc([
    "Executive Summary",
    "Market Analysis",
    "Product Strategy",
    "Business Model",
    "Go-to-Market",
    "Financial Projections",
    "Team & Timeline",
    "Investment Ask"
  ]);

  addSectionSlide("01", "Executive Summary", [
    { type: 'bullet', text: 'This is a concise overview of the key points' },
    { type: 'bullet', text: 'Highlight the main value proposition' },
    { type: 'callout', text: 'Key insight: Focus on what makes this opportunity unique' }
  ]);

  addSectionSlide("02", "Market Analysis", [
    { type: 'bullet', text: 'Target market size and growth trends' },
    { type: 'bullet', text: 'Customer segmentation and pain points' },
    { type: 'bullet', text: 'Competitive landscape overview' }
  ]);

  addTableSlide("Market Data", ["Metric", "Value", "Source"], [
    ["TAM", "$10B", "Industry Report"],
    ["SAM", "$2B", "Company Analysis"],
    ["SOM", "$500M", "Conservative Est."]
  ]);

  addSectionSlide("03", "Product Strategy", [
    { type: 'bullet', text: 'Core product features and differentiation' },
    { type: 'bullet', text: 'Technology stack and innovation' },
    { type: 'bullet', text: 'Roadmap and development milestones' }
  ]);

  addSectionSlide("04", "Business Model", [
    { type: 'bullet', text: 'Revenue streams and pricing strategy' },
    { type: 'bullet', text: 'Unit economics and margins' },
    { type: 'bullet', text: 'Customer acquisition strategy' }
  ]);

  addThankYou("Ready to discuss how we can create value together.");
}

if (require.main === module) {
  generateDefaultPresentation();
  pres.writeFile({ fileName: output })
    .then(() => console.log("Generated:", output))
    .catch(err => console.error("Error:", err));
}

module.exports = { pres, theme, addCover, addToc, addSectionSlide, addTableSlide, addThankYou };